# Generated by Django 3.2 on 2022-09-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['room'], 'verbose_name': 'rooms', 'verbose_name_plural': 'room'},
        ),
    ]
