# Generated by Django 3.2 on 2022-09-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together={('arrival_date', 'departure_date')},
        ),
    ]
