# Generated by Django 3.2 on 2022-09-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='create_at',
        ),
    ]
